### ISSUE TITLE
repair setships

### ISSUE THREAD

**Issue by qwergram** [qwergram/cs132-Project1#5]
[Line 350 in fleet.cpp](https://github.com/qwergram/cs132-Project1/blob/master/SinkTheFleet/fleet.cpp#L350)

**Comment by TabithaRoemish** [comment]
I'm working on writing this but I'm having trouble calling if from main. it's saying that setShips is undefined and I don't know why. can you call setships from main? Even if it's not completed the project should build and then fail when it gets to setShips but I can't even get it to build.

Also here's the code for setShips but I need to test it:
// your code goes here ...
		int row = players[whichPlayer].m_ships[shipIndex].m_bowLocation.m_row;
		int col = players[whichPlayer].m_ships[shipIndex].m_bowLocation.m_col;
		if (players[whichPlayer].m_ships[shipIndex].m_orientation == VERTICAL)
		{
			for (int shipSizeIndex = 0; shipSizeIndex < shipSize[shipIndex]; shipSizeIndex++)
				players[whichPlayer].m_gameGrid[0][row + shipSizeIndex][col] = players[whichPlayer].m_ships[shipIndex].m_name;
		}
		else // if horizontal
		{
			for (int shipSizeIndex = 0; shipSizeIndex < shipSize[shipIndex]; shipSizeIndex++)
				players[whichPlayer].m_gameGrid[0][row][col + shipSizeIndex] = players[whichPlayer].m_ships[shipIndex].m_name;
		}
